services:
  db:
    image: postgres:17.3-alpine3.20
    ports:
      - "5432:5432"
    volumes:
      - roomiefunds-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DATABASE: app
  sso:
    image: quay.io/keycloak/keycloak:26.0.7
    ports:
      - "9090:8080"
    command: [ "start-dev", "--import-realm" ]
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin

volumes:
  roomiefunds-db:
