quarkus.banner.path=banner.txt

# Quarkus Datenbank Konfiguration
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=app
quarkus.datasource.password=app
quarkus.datasource.jdbc.url=jdbc:postgresql://127.0.0.1:5432/app
quarkus.datasource.jdbc.min-size=2
quarkus.datasource.jdbc.max-size=16
quarkus.flyway.migrate-at-start=true

# Quarkus CORS
quarkus.http.cors=true
quarkus.http.cors.origins=http://127.0.0.1:5173,http://localhost:5173
quarkus.http.cors.headers=accept, origin, authorization, content-type, x-requested-with
quarkus.http.cors.methods=GET,POST,PATCH,DELETE,OPTIONS

# OIDC Configuration
quarkus.oidc.auth-server-url=https://auth.flur4.de/realms/flur4.de
quarkus.oidc.client-id=roomiefunds
quarkus.oidc.credentials.secret=hQwIawsStKougwdce0qjUCNgKf9ExbJJ

# Keycloak Service Account Configuration
quarkus.keycloak.admin-client.server-url=https://auth.flur4.de
quarkus.keycloak.admin-client.realm=demo-realm
quarkus.keycloak.admin-client.client-id=roomiefunds-svc
quarkus.keycloak.admin-client.client-secret=${KC_SVC_CLIENT_SECRET}
quarkus.keycloak.admin-client.grant-type=CLIENT_CREDENTIALS

# Keycloak sync configuration
app.keycloak.sync.realm=demo-realm
app.keycloak.sync.floor-member-group=floor-members
app.keycloak.sync.admin-group=roomiefunds-admin
app.keycloak.sync.attribute.room=room
app.keycloak.sync.attribute.is-current-tenant=isCurrentTenant

# Disable analytics and jooq tip of the day
quarkus.log.category."org.jooq.Constants".level=OFF
quarkus.analytics.disabled=true

# default jOOQ datasource
quarkus.jooq.dialect=POSTGRES

# EnableBanking REST client base URL
quarkus.rest-client."de.flur4.roomiefunds.infrastructure.webclient.enablebanking.EnableBankingClient".url=https://api.enablebanking.com
quarkus.rest-client.http2=true

# Configure EnableBanking things
app.enablebanking.applicationid=e281444e-16e4-4d92-8bea-08d7f461e213
app.enablebanking.privatekey.path=/home/user/Downloads/enablebanking/private.key
app.enablebanking.publickey.path=/home/user/Downloads/enablebanking/public.crt
app.backend.baseurl=http://localhost:8080
app.frontend.baseurl=http://localhost:5173
app.email.replyto=test@test.com

quarkus.rest-client.logging.scope=request-response
quarkus.log.category."org.jboss.resteasy.reactive.client.logging".level=DEBUG
quarkus.rest-client.logging.body-limit=1000
quarkus.log.console.level=DEBUG
quarkus.http.host=0.0.0.0

# Quarkus Mailer Configuration
quarkus.mailer.from=test@test.com
quarkus.mailer.host=mail.test.de
quarkus.mailer.port=465
quarkus.mailer.tls=true
quarkus.mailer.username=test
quarkus.mailer.password=test
quarkus.mailer.log-rejected-recipients=true

# Quarkus Container options
quarkus.container-image.registry=ghcr.io
quarkus.container-image.group=fatihcatalkaya
quarkus.container-image.name=roomiefunds
quarkus.container-image.build=true
quarkus.container-image.push=false
