// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-fetch';
import type { GetData, GetApiProductData, GetApiProductResponse, PostApiProductData, PostApiProductResponse, DeleteApiProductByProductIdDData, DeleteApiProductByProductIdDResponse, GetApiProductByProductIdDData, GetApiProductByProductIdDResponse, PatchApiProductByProductIdDData, PatchApiProductByProductIdDResponse, GetByFileNameData } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get Frontend Root
 */
export const get = <ThrowOnError extends boolean = false>(options?: Options<GetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
        url: '/',
        ...options
    });
};

/**
 * Get Products
 */
export const getApiProduct = <ThrowOnError extends boolean = false>(options?: Options<GetApiProductData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetApiProductResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/product',
        ...options
    });
};

/**
 * Create Product
 */
export const postApiProduct = <ThrowOnError extends boolean = false>(options: Options<PostApiProductData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<PostApiProductResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/product',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Delete Product
 */
export const deleteApiProductByProductIdD = <ThrowOnError extends boolean = false>(options: Options<DeleteApiProductByProductIdDData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<DeleteApiProductByProductIdDResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/product/{productId}:\\d+',
        ...options
    });
};

/**
 * Get Product
 */
export const getApiProductByProductIdD = <ThrowOnError extends boolean = false>(options: Options<GetApiProductByProductIdDData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetApiProductByProductIdDResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/product/{productId}:\\d+',
        ...options
    });
};

/**
 * Patch Product
 */
export const patchApiProductByProductIdD = <ThrowOnError extends boolean = false>(options: Options<PatchApiProductByProductIdDData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).patch<PatchApiProductByProductIdDResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/product/{productId}:\\d+',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Get Frontend Static File
 */
export const getByFileName = <ThrowOnError extends boolean = false>(options: Options<GetByFileNameData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
        url: '/{fileName}',
        ...options
    });
};