// This file is auto-generated by @hey-api/openapi-ts

export type CreateProductDto = {
    name: string;
    price?: number;
};

export type Product = {
    id?: number;
    name?: string;
    price?: number;
};

export type UpdateProductDto = {
    name?: string | null;
    price?: number | null;
};

export type GetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type GetResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiProductData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/product';
};

export type GetApiProductErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type GetApiProductResponses = {
    /**
     * OK
     */
    200: Array<Product>;
};

export type GetApiProductResponse = GetApiProductResponses[keyof GetApiProductResponses];

export type PostApiProductData = {
    body: CreateProductDto;
    path?: never;
    query?: never;
    url: '/api/product';
};

export type PostApiProductErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type PostApiProductResponses = {
    /**
     * OK
     */
    200: Product;
};

export type PostApiProductResponse = PostApiProductResponses[keyof PostApiProductResponses];

export type DeleteApiProductByProductIdDData = {
    body?: never;
    path: {
        productId: number;
    };
    query?: never;
    url: '/api/product/{productId}:\\d+';
};

export type DeleteApiProductByProductIdDErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type DeleteApiProductByProductIdDResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteApiProductByProductIdDResponse = DeleteApiProductByProductIdDResponses[keyof DeleteApiProductByProductIdDResponses];

export type GetApiProductByProductIdDData = {
    body?: never;
    path: {
        productId: number;
    };
    query?: never;
    url: '/api/product/{productId}:\\d+';
};

export type GetApiProductByProductIdDErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type GetApiProductByProductIdDResponses = {
    /**
     * OK
     */
    200: Product;
};

export type GetApiProductByProductIdDResponse = GetApiProductByProductIdDResponses[keyof GetApiProductByProductIdDResponses];

export type PatchApiProductByProductIdDData = {
    body: UpdateProductDto;
    path: {
        productId: number;
    };
    query?: never;
    url: '/api/product/{productId}:\\d+';
};

export type PatchApiProductByProductIdDErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type PatchApiProductByProductIdDResponses = {
    /**
     * OK
     */
    200: Product;
};

export type PatchApiProductByProductIdDResponse = PatchApiProductByProductIdDResponses[keyof PatchApiProductByProductIdDResponses];

export type GetByFileNameData = {
    body?: never;
    path: {
        fileName: string;
    };
    query?: never;
    url: '/{fileName}';
};

export type GetByFileNameResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: 'http://localhost:8080' | (string & {});
};