// This file is auto-generated by @hey-api/openapi-ts

export type Aspsp = {
	name?: string;
	country?: string;
};

export type AspspData = {
	name?: string;
	country?: string;
	logo?: string;
	psu_types?: Array<PsuType>;
	auth_methods?: Array<AuthMethod>;
	maximum_consent_validity?: number;
	beta?: boolean;
};

export type Account = {
	id?: number;
	name?: string;
	active?: boolean;
};

export type AccountWithBalance = {
	id?: number;
	name?: string;
	active?: boolean;
	balance?: number;
};

export type AddPersonToGroupRequest = {
	personId?: number;
};

export type AuthMethod = {
	name?: string;
	title?: string;
	psu_type?: PsuType;
	credentials?: Array<Credential>;
	approach?: AuthenticationApproach;
	hidden_method?: boolean;
};

export type AuthenticationApproach = 'REDIRECT' | 'DECOUPLED' | 'EMBEDDED';

export type CreateAccountDto = {
	name: string;
	active: boolean;
};

export type CreateGroupDto = {
	name: string;
	keycloakGroupId?: string;
};

export type CreatePersonDto = {
	firstName: string;
	lastName: string;
	room: string;
	email?: string | null;
	paysFloorFees: boolean;
	printOnProductTallyList: boolean;
	emailAccountStatement: boolean;
};

export type CreateProductDto = {
	name: string;
	price?: number;
	print?: boolean;
};

export type CreateRecurringTransactionDto = {
	amount?: number;
	sourceAccountId?: number;
	targetAccountId?: number;
	valueDayOfMonth?: number;
	name: string;
	transactionDescription: string;
};

export type CreateTransactionDto = {
	sourceAccountId?: number;
	targetAccountId?: number;
	amount?: number;
	valueDate?: LocalDate;
	description: string;
};

export type Credential = {
	name?: string;
	title?: string;
	required?: boolean;
	description?: string;
};

export type EnableBankingAccountDto = {
	id?: number;
	uid?: string;
	iban?: string;
};

export type EnableBankingSession = {
	id?: number;
	validUntil?: OffsetDateTime;
	bankName?: string;
	bankAccountIban?: string;
	bankAccountUid?: string;
	accountId?: number;
};

export type EnableBankingUnfinishedSession = {
	unfinishedSessionId?: number;
	validUntil?: OffsetDateTime;
	bankName?: string;
	accounts?: Array<EnableBankingAccountDto>;
};

export type FinishSessionRequest = {
	bankAccountIban: string;
	bankAccountUid: string;
	accountId: number;
};

export type Flurbeitrag = {
	flurbeitrag?: number;
};

export type GetAspspResponse = {
	aspsps?: Array<AspspData>;
};

export type GetRecurringTransactionDto = {
	id?: number;
	amount?: number;
	sourceAccountId?: number;
	sourceAccountName?: string;
	sourceAccountActive?: boolean;
	targetAccountId?: number;
	targetAccountName?: string;
	targetAccountActive?: boolean;
	valueDayOfMonth?: number;
	name?: string;
	transactionDescription?: string;
};

export type Group = {
	id?: number;
	name?: string;
	keycloakGroupId?: string;
};

export type LocalDate = string;

export type LogEntryDto = {
	id?: number;
	createdAt?: OffsetDateTime;
	logOperation?: LogOperations;
	modifiedTableName?: string;
	modifiedBy?: string;
	subjectBeforeJson?: string;
	subjectAfterJson?: string;
};

export type LogOperations = 'create' | 'update' | 'delete';

export type OffsetDateTime = string;

export type PsuType = 'BUSINESS' | 'PERSONAL';

export type Person = {
	id?: number;
	firstName?: string;
	lastName?: string;
	room?: string;
	paysFloorFees?: boolean;
	accountId?: number;
	printOnProductTallyList?: boolean;
	email?: string;
	emailAccountStatement?: boolean;
	keycloakUserId?: string;
};

export type Product = {
	id?: number;
	name?: string;
	price?: number;
	print?: boolean;
	sortOrder?: number;
};

export type StartAuthorizationDto = {
	aspsp?: Aspsp;
	maximumConsentValidity?: number;
	authMethod?: string;
};

export type StartAuthorizationResponse = {
	url?: string;
	authorization_id?: string;
	psu_id_hash?: string;
};

export type Transaction = {
	id?: number;
	sourceAccountId?: number;
	sourceAccountName?: string;
	sourceAccountActive?: boolean;
	targetAccountId?: number;
	targetAccountName?: string;
	targetAccountActive?: boolean;
	amount?: number;
	createdAt?: OffsetDateTime;
	valueDate?: LocalDate;
	description?: string;
	hasReceipt?: boolean;
};

export type TransactionSaldoDto = {
	transaction?: Transaction;
	saldo?: number;
	sourceAccountNameParts?: Array<string>;
	targetAccountNameParts?: Array<string>;
};

export type UpdateAccountDto = {
	name?: string | null;
	active?: boolean | null;
};

export type UpdateGroupDto = {
	name?: string | null;
	keycloakGroupId?: string | null;
};

export type UpdatePersonDto = {
	firstName?: string | null;
	lastName?: string | null;
	room?: string | null;
	paysFloorFees?: boolean | null;
	printOnProductTallyList?: boolean | null;
	email?: string | null;
	emailAccountStatement?: boolean | null;
};

export type UpdateProductDto = {
	name?: string | null;
	price?: number | null;
	print?: boolean | null;
};

export type UpdateRecurringTransactionDto = {
	amount?: number | null;
	sourceAccountId?: number | null;
	targetAccountId?: number | null;
	valueDayOfMonth?: number | null;
	name?: string | null;
	transactionDescription?: string | null;
};

export type UpdateTransactionDto = {
	sourceAccountId?: number | null;
	targetAccountId?: number | null;
	amount?: number | null;
	valueDate?: LocalDate | null;
	description?: string | null;
};

export type GetData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/';
};

export type GetResponses = {
	/**
	 * OK
	 */
	200: unknown;
};

export type GetApiAccountData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/api/account';
};

export type GetApiAccountErrors = {
	/**
	 * Not Authorized
	 */
	401: unknown;
	/**
	 * Not Allowed
	 */
	403: unknown;
};

export type GetApiAccountResponses = {
	/**
	 * OK
	 */
	200: Array<Account>;
};

export type GetApiAccountResponse = GetApiAccountResponses[keyof GetApiAccountResponses];

export type PostApiAccountData = {
	body: CreateAccountDto;
	path?: never;
	query?: never;
	url: '/api/account';
};

export type PostApiAccountErrors = {
	/**
	 * Bad Request
	 */
	400: unknown;
	/**
	 * Not Authorized
	 */
	401: unknown;
	/**
	 * Not Allowed
	 */
	403: unknown;
};

export type PostApiAccountResponses = {
	/**
	 * OK
	 */
	200: Account;
};

export type PostApiAccountResponse = PostApiAccountResponses[keyof PostApiAccountResponses];

export type GetApiAccountReportData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/api/account/report';
};

export type GetApiAccountReportErrors = {
	/**
	 * Not Authorized
	 */
	401: unknown;
	/**
	 * Not Allowed
	 */
	403: unknown;
};

export type GetApiAccountReportResponses = {
	/**
	 * OK
	 */
	200: Blob | File;
};

export type GetApiAccountReportResponse =
	GetApiAccountReportResponses[keyof GetApiAccountReportResponses];

export type GetApiAccountSendAccountStatementsNowData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/api/account/send-account-statements-now';
};

export type GetApiAccountSendAccountStatementsNowErrors = {
	/**
	 * Not Authorized
	 */
	401: unknown;
	/**
	 * Not Allowed
	 */
	403: unknown;
};

export type GetApiAccountSendAccountStatementsNowResponses = {
	/**
	 * OK
	 */
	200: unknown;
};

export type GetApiAccountWithBalancesData = {
	body?: never;
	path?: never;
	query?: {
		'include-disabled'?: boolean;
	};
	url: '/api/account/with-balances';
};

export type GetApiAccountWithBalancesErrors = {
	/**
	 * Not Authorized
	 */
	401: unknown;
	/**
	 * Not Allowed
	 */
	403: unknown;
};

export type GetApiAccountWithBalancesResponses = {
	/**
	 * OK
	 */
	200: Array<AccountWithBalance>;
};

export type GetApiAccountWithBalancesResponse =
	GetApiAccountWithBalancesResponses[keyof GetApiAccountWithBalancesResponses];

export type DeleteApiAccountByAccountIdData = {
	body?: never;
	path: {
		accountId: number;
	};
	query?: never;
	url: '/api/account/{accountId}';
};

export type DeleteApiAccountByAccountIdErrors = {
	/**
	 * Not Authorized
	 */
	401: unknown;
	/**
	 * Not Allowed
	 */
	403: unknown;
};

export type DeleteApiAccountByAccountIdResponses = {
	/**
	 * No Content
	 */
	204: void;
};

export type DeleteApiAccountByAccountIdResponse =
	DeleteApiAccountByAccountIdResponses[keyof DeleteApiAccountByAccountIdResponses];

export type GetApiAccountByAccountIdData = {
	body?: never;
	path: {
		accountId: number;
	};
	query?: never;
	url: '/api/account/{accountId}';
};

export type GetApiAccountByAccountIdErrors = {
	/**
	 * Not Authorized
	 */
	401: unknown;
	/**
	 * Not Allowed
	 */
	403: unknown;
};

export type GetApiAccountByAccountIdResponses = {
	/**
	 * OK
	 */
	200: Account;
};

export type GetApiAccountByAccountIdResponse =
	GetApiAccountByAccountIdResponses[keyof GetApiAccountByAccountIdResponses];

export type PatchApiAccountByAccountIdData = {
	body: UpdateAccountDto;
	path: {
		accountId: number;
	};
	query?: never;
	url: '/api/account/{accountId}';
};

export type PatchApiAccountByAccountIdErrors = {
	/**
	 * Not Authorized
	 */
	401: unknown;
	/**
	 * Not Allowed
	 */
	403: unknown;
};

export type PatchApiAccountByAccountIdResponses = {
	/**
	 * OK
	 */
	200: Account;
};

export type PatchApiAccountByAccountIdResponse =
	PatchApiAccountByAccountIdResponses[keyof PatchApiAccountByAccountIdResponses];

export type GetApiAccountByAccountIdStatementData = {
	body?: never;
	path: {
		accountId: number;
	};
	query?: never;
	url: '/api/account/{accountId}/statement';
};

export type GetApiAccountByAccountIdStatementErrors = {
	/**
	 * Not Authorized
	 */
	401: unknown;
	/**
	 * Not Allowed
	 */
	403: unknown;
};

export type GetApiAccountByAccountIdStatementResponses = {
	/**
	 * OK
	 */
	200: Blob | File;
};

export type GetApiAccountByAccountIdStatementResponse =
	GetApiAccountByAccountIdStatementResponses[keyof GetApiAccountByAccountIdStatementResponses];

export type GetApiEnablebankingData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/api/enablebanking';
};

export type GetApiEnablebankingErrors = {
	/**
	 * Not Authorized
	 */
	401: unknown;
	/**
	 * Not Allowed
	 */
	403: unknown;
};

export type GetApiEnablebankingResponses = {
	/**
	 * OK
	 */
	200: GetAspspResponse;
};

export type GetApiEnablebankingResponse =
	GetApiEnablebankingResponses[keyof GetApiEnablebankingResponses];

export type PostApiEnablebankingData = {
	body: StartAuthorizationDto;
	path?: never;
	query?: never;
	url: '/api/enablebanking';
};

export type PostApiEnablebankingErrors = {
	/**
	 * Bad Request
	 */
	400: unknown;
	/**
	 * Not Authorized
	 */
	401: unknown;
	/**
	 * Not Allowed
	 */
	403: unknown;
};

export type PostApiEnablebankingResponses = {
	/**
	 * OK
	 */
	200: StartAuthorizationResponse;
};

export type PostApiEnablebankingResponse =
	PostApiEnablebankingResponses[keyof PostApiEnablebankingResponses];

export type GetApiEnablebankingEndData = {
	body?: never;
	path?: never;
	query?: {
		code?: string;
	};
	url: '/api/enablebanking/end';
};

export type GetApiEnablebankingEndResponses = {
	/**
	 * OK
	 */
	200: unknown;
};

export type GetApiEnablebankingSessionData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/api/enablebanking/session';
};

export type GetApiEnablebankingSessionErrors = {
	/**
	 * Not Authorized
	 */
	401: unknown;
	/**
	 * Not Allowed
	 */
	403: unknown;
};

export type GetApiEnablebankingSessionResponses = {
	/**
	 * OK
	 */
	200: Array<EnableBankingSession>;
};

export type GetApiEnablebankingSessionResponse =
	GetApiEnablebankingSessionResponses[keyof GetApiEnablebankingSessionResponses];

export type GetApiEnablebankingSessionUnfinishedBySessionIdData = {
	body?: never;
	path: {
		sessionId: number;
	};
	query?: never;
	url: '/api/enablebanking/session/unfinished/{sessionId}';
};

export type GetApiEnablebankingSessionUnfinishedBySessionIdErrors = {
	/**
	 * Not Authorized
	 */
	401: unknown;
	/**
	 * Not Allowed
	 */
	403: unknown;
};

export type GetApiEnablebankingSessionUnfinishedBySessionIdResponses = {
	/**
	 * OK
	 */
	200: EnableBankingUnfinishedSession;
};

export type GetApiEnablebankingSessionUnfinishedBySessionIdResponse =
	GetApiEnablebankingSessionUnfinishedBySessionIdResponses[keyof GetApiEnablebankingSessionUnfinishedBySessionIdResponses];

export type PostApiEnablebankingSessionUnfinishedBySessionIdData = {
	body: FinishSessionRequest;
	path: {
		sessionId: number;
	};
	query?: never;
	url: '/api/enablebanking/session/unfinished/{sessionId}';
};

export type PostApiEnablebankingSessionUnfinishedBySessionIdErrors = {
	/**
	 * Bad Request
	 */
	400: unknown;
	/**
	 * Not Authorized
	 */
	401: unknown;
	/**
	 * Not Allowed
	 */
	403: unknown;
};

export type PostApiEnablebankingSessionUnfinishedBySessionIdResponses = {
	/**
	 * OK
	 */
	200: EnableBankingSession;
};

export type PostApiEnablebankingSessionUnfinishedBySessionIdResponse =
	PostApiEnablebankingSessionUnfinishedBySessionIdResponses[keyof PostApiEnablebankingSessionUnfinishedBySessionIdResponses];

export type DeleteApiEnablebankingUnfinishedSessionBySessionIdData = {
	body?: never;
	path: {
		sessionId: number;
	};
	query?: never;
	url: '/api/enablebanking/unfinished-session/{sessionId}';
};

export type DeleteApiEnablebankingUnfinishedSessionBySessionIdErrors = {
	/**
	 * Not Authorized
	 */
	401: unknown;
	/**
	 * Not Allowed
	 */
	403: unknown;
};

export type DeleteApiEnablebankingUnfinishedSessionBySessionIdResponses = {
	/**
	 * No Content
	 */
	204: void;
};

export type DeleteApiEnablebankingUnfinishedSessionBySessionIdResponse =
	DeleteApiEnablebankingUnfinishedSessionBySessionIdResponses[keyof DeleteApiEnablebankingUnfinishedSessionBySessionIdResponses];

export type GetApiFlurbeitragData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/api/flurbeitrag';
};

export type GetApiFlurbeitragErrors = {
	/**
	 * Not Authorized
	 */
	401: unknown;
	/**
	 * Not Allowed
	 */
	403: unknown;
};

export type GetApiFlurbeitragResponses = {
	/**
	 * OK
	 */
	200: Flurbeitrag;
};

export type GetApiFlurbeitragResponse =
	GetApiFlurbeitragResponses[keyof GetApiFlurbeitragResponses];

export type PutApiFlurbeitragData = {
	body: Flurbeitrag;
	path?: never;
	query?: never;
	url: '/api/flurbeitrag';
};

export type PutApiFlurbeitragErrors = {
	/**
	 * Bad Request
	 */
	400: unknown;
	/**
	 * Not Authorized
	 */
	401: unknown;
	/**
	 * Not Allowed
	 */
	403: unknown;
};

export type PutApiFlurbeitragResponses = {
	/**
	 * No Content
	 */
	204: void;
};

export type PutApiFlurbeitragResponse =
	PutApiFlurbeitragResponses[keyof PutApiFlurbeitragResponses];

export type GetApiGroupData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/api/group';
};

export type GetApiGroupErrors = {
	/**
	 * Not Authorized
	 */
	401: unknown;
	/**
	 * Not Allowed
	 */
	403: unknown;
};

export type GetApiGroupResponses = {
	/**
	 * OK
	 */
	200: Array<Group>;
};

export type GetApiGroupResponse = GetApiGroupResponses[keyof GetApiGroupResponses];

export type PostApiGroupData = {
	body: CreateGroupDto;
	path?: never;
	query?: never;
	url: '/api/group';
};

export type PostApiGroupErrors = {
	/**
	 * Bad Request
	 */
	400: unknown;
	/**
	 * Not Authorized
	 */
	401: unknown;
	/**
	 * Not Allowed
	 */
	403: unknown;
};

export type PostApiGroupResponses = {
	/**
	 * OK
	 */
	200: Group;
};

export type PostApiGroupResponse = PostApiGroupResponses[keyof PostApiGroupResponses];

export type DeleteApiGroupByGroupIdData = {
	body?: never;
	path: {
		groupId: number;
	};
	query?: never;
	url: '/api/group/{groupId}';
};

export type DeleteApiGroupByGroupIdErrors = {
	/**
	 * Not Authorized
	 */
	401: unknown;
	/**
	 * Not Allowed
	 */
	403: unknown;
};

export type DeleteApiGroupByGroupIdResponses = {
	/**
	 * No Content
	 */
	204: void;
};

export type DeleteApiGroupByGroupIdResponse =
	DeleteApiGroupByGroupIdResponses[keyof DeleteApiGroupByGroupIdResponses];

export type GetApiGroupByGroupIdData = {
	body?: never;
	path: {
		groupId: number;
	};
	query?: never;
	url: '/api/group/{groupId}';
};

export type GetApiGroupByGroupIdErrors = {
	/**
	 * Not Authorized
	 */
	401: unknown;
	/**
	 * Not Allowed
	 */
	403: unknown;
};

export type GetApiGroupByGroupIdResponses = {
	/**
	 * OK
	 */
	200: Group;
};

export type GetApiGroupByGroupIdResponse =
	GetApiGroupByGroupIdResponses[keyof GetApiGroupByGroupIdResponses];

export type PatchApiGroupByGroupIdData = {
	body: UpdateGroupDto;
	path: {
		groupId: number;
	};
	query?: never;
	url: '/api/group/{groupId}';
};

export type PatchApiGroupByGroupIdErrors = {
	/**
	 * Not Authorized
	 */
	401: unknown;
	/**
	 * Not Allowed
	 */
	403: unknown;
};

export type PatchApiGroupByGroupIdResponses = {
	/**
	 * OK
	 */
	200: Group;
};

export type PatchApiGroupByGroupIdResponse =
	PatchApiGroupByGroupIdResponses[keyof PatchApiGroupByGroupIdResponses];

export type GetApiGroupByGroupIdPersonsData = {
	body?: never;
	path: {
		groupId: number;
	};
	query?: never;
	url: '/api/group/{groupId}/persons';
};

export type GetApiGroupByGroupIdPersonsErrors = {
	/**
	 * Not Authorized
	 */
	401: unknown;
	/**
	 * Not Allowed
	 */
	403: unknown;
};

export type GetApiGroupByGroupIdPersonsResponses = {
	/**
	 * OK
	 */
	200: Array<Person>;
};

export type GetApiGroupByGroupIdPersonsResponse =
	GetApiGroupByGroupIdPersonsResponses[keyof GetApiGroupByGroupIdPersonsResponses];

export type PostApiGroupByGroupIdPersonsData = {
	body: AddPersonToGroupRequest;
	path: {
		groupId: number;
	};
	query?: never;
	url: '/api/group/{groupId}/persons';
};

export type PostApiGroupByGroupIdPersonsErrors = {
	/**
	 * Bad Request
	 */
	400: unknown;
	/**
	 * Not Authorized
	 */
	401: unknown;
	/**
	 * Not Allowed
	 */
	403: unknown;
};

export type PostApiGroupByGroupIdPersonsResponses = {
	/**
	 * Created
	 */
	201: unknown;
};

export type DeleteApiGroupByGroupIdPersonsByPersonIdData = {
	body?: never;
	path: {
		groupId: number;
		personId: number;
	};
	query?: never;
	url: '/api/group/{groupId}/persons/{personId}';
};

export type DeleteApiGroupByGroupIdPersonsByPersonIdErrors = {
	/**
	 * Not Authorized
	 */
	401: unknown;
	/**
	 * Not Allowed
	 */
	403: unknown;
};

export type DeleteApiGroupByGroupIdPersonsByPersonIdResponses = {
	/**
	 * No Content
	 */
	204: void;
};

export type DeleteApiGroupByGroupIdPersonsByPersonIdResponse =
	DeleteApiGroupByGroupIdPersonsByPersonIdResponses[keyof DeleteApiGroupByGroupIdPersonsByPersonIdResponses];

export type PostApiKeycloakSyncFullData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/api/keycloak-sync/full';
};

export type PostApiKeycloakSyncFullErrors = {
	/**
	 * Not Authorized
	 */
	401: unknown;
	/**
	 * Not Allowed
	 */
	403: unknown;
};

export type PostApiKeycloakSyncFullResponses = {
	/**
	 * Created
	 */
	201: unknown;
};

export type GetApiKontoFlurkontoData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/api/konto/flurkonto';
};

export type GetApiKontoFlurkontoErrors = {
	/**
	 * Not Authorized
	 */
	401: unknown;
	/**
	 * Not Allowed
	 */
	403: unknown;
};

export type GetApiKontoFlurkontoResponses = {
	/**
	 * OK
	 */
	200: Account | null;
};

export type GetApiKontoFlurkontoResponse =
	GetApiKontoFlurkontoResponses[keyof GetApiKontoFlurkontoResponses];

export type PutApiKontoFlurkontoData = {
	body: number;
	path?: never;
	query?: never;
	url: '/api/konto/flurkonto';
};

export type PutApiKontoFlurkontoErrors = {
	/**
	 * Not Authorized
	 */
	401: unknown;
	/**
	 * Not Allowed
	 */
	403: unknown;
};

export type PutApiKontoFlurkontoResponses = {
	/**
	 * OK
	 */
	200: Account;
};

export type PutApiKontoFlurkontoResponse =
	PutApiKontoFlurkontoResponses[keyof PutApiKontoFlurkontoResponses];

export type GetApiKontoGetraenkekontoData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/api/konto/getraenkekonto';
};

export type GetApiKontoGetraenkekontoErrors = {
	/**
	 * Not Authorized
	 */
	401: unknown;
	/**
	 * Not Allowed
	 */
	403: unknown;
};

export type GetApiKontoGetraenkekontoResponses = {
	/**
	 * OK
	 */
	200: Account | null;
};

export type GetApiKontoGetraenkekontoResponse =
	GetApiKontoGetraenkekontoResponses[keyof GetApiKontoGetraenkekontoResponses];

export type PutApiKontoGetraenkekontoData = {
	body: number;
	path?: never;
	query?: never;
	url: '/api/konto/getraenkekonto';
};

export type PutApiKontoGetraenkekontoErrors = {
	/**
	 * Not Authorized
	 */
	401: unknown;
	/**
	 * Not Allowed
	 */
	403: unknown;
};

export type PutApiKontoGetraenkekontoResponses = {
	/**
	 * OK
	 */
	200: Account;
};

export type PutApiKontoGetraenkekontoResponse =
	PutApiKontoGetraenkekontoResponses[keyof PutApiKontoGetraenkekontoResponses];

export type GetApiLogData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/api/log';
};

export type GetApiLogErrors = {
	/**
	 * Not Authorized
	 */
	401: unknown;
	/**
	 * Not Allowed
	 */
	403: unknown;
};

export type GetApiLogResponses = {
	/**
	 * OK
	 */
	200: Array<LogEntryDto>;
};

export type GetApiLogResponse = GetApiLogResponses[keyof GetApiLogResponses];

export type GetApiLogAccountTransactionsByAccountIdData = {
	body?: never;
	path: {
		account_id: string;
	};
	query?: never;
	url: '/api/log/account-transactions/{account_id}';
};

export type GetApiLogAccountTransactionsByAccountIdErrors = {
	/**
	 * Not Authorized
	 */
	401: unknown;
	/**
	 * Not Allowed
	 */
	403: unknown;
};

export type GetApiLogAccountTransactionsByAccountIdResponses = {
	/**
	 * OK
	 */
	200: Array<LogEntryDto>;
};

export type GetApiLogAccountTransactionsByAccountIdResponse =
	GetApiLogAccountTransactionsByAccountIdResponses[keyof GetApiLogAccountTransactionsByAccountIdResponses];

export type GetApiLogByTableNameData = {
	body?: never;
	path: {
		table_name: string;
	};
	query?: never;
	url: '/api/log/{table_name}';
};

export type GetApiLogByTableNameErrors = {
	/**
	 * Not Authorized
	 */
	401: unknown;
	/**
	 * Not Allowed
	 */
	403: unknown;
};

export type GetApiLogByTableNameResponses = {
	/**
	 * OK
	 */
	200: Array<LogEntryDto>;
};

export type GetApiLogByTableNameResponse =
	GetApiLogByTableNameResponses[keyof GetApiLogByTableNameResponses];

export type GetApiLogByTableNameByObjectIdData = {
	body?: never;
	path: {
		object_id: string;
		table_name: string;
	};
	query?: never;
	url: '/api/log/{table_name}/{object_id}';
};

export type GetApiLogByTableNameByObjectIdErrors = {
	/**
	 * Not Authorized
	 */
	401: unknown;
	/**
	 * Not Allowed
	 */
	403: unknown;
};

export type GetApiLogByTableNameByObjectIdResponses = {
	/**
	 * OK
	 */
	200: Array<LogEntryDto>;
};

export type GetApiLogByTableNameByObjectIdResponse =
	GetApiLogByTableNameByObjectIdResponses[keyof GetApiLogByTableNameByObjectIdResponses];

export type GetApiPersonData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/api/person';
};

export type GetApiPersonErrors = {
	/**
	 * Not Authorized
	 */
	401: unknown;
	/**
	 * Not Allowed
	 */
	403: unknown;
};

export type GetApiPersonResponses = {
	/**
	 * OK
	 */
	200: Array<Person>;
};

export type GetApiPersonResponse = GetApiPersonResponses[keyof GetApiPersonResponses];

export type PostApiPersonData = {
	body: CreatePersonDto;
	path?: never;
	query?: never;
	url: '/api/person';
};

export type PostApiPersonErrors = {
	/**
	 * Bad Request
	 */
	400: unknown;
	/**
	 * Not Authorized
	 */
	401: unknown;
	/**
	 * Not Allowed
	 */
	403: unknown;
};

export type PostApiPersonResponses = {
	/**
	 * OK
	 */
	200: Person;
};

export type PostApiPersonResponse = PostApiPersonResponses[keyof PostApiPersonResponses];

export type DeleteApiPersonByPersonIdData = {
	body?: never;
	path: {
		personId: number;
	};
	query?: never;
	url: '/api/person/{personId}';
};

export type DeleteApiPersonByPersonIdErrors = {
	/**
	 * Not Authorized
	 */
	401: unknown;
	/**
	 * Not Allowed
	 */
	403: unknown;
};

export type DeleteApiPersonByPersonIdResponses = {
	/**
	 * No Content
	 */
	204: void;
};

export type DeleteApiPersonByPersonIdResponse =
	DeleteApiPersonByPersonIdResponses[keyof DeleteApiPersonByPersonIdResponses];

export type GetApiPersonByPersonIdData = {
	body?: never;
	path: {
		personId: number;
	};
	query?: never;
	url: '/api/person/{personId}';
};

export type GetApiPersonByPersonIdErrors = {
	/**
	 * Not Authorized
	 */
	401: unknown;
	/**
	 * Not Allowed
	 */
	403: unknown;
};

export type GetApiPersonByPersonIdResponses = {
	/**
	 * OK
	 */
	200: Person;
};

export type GetApiPersonByPersonIdResponse =
	GetApiPersonByPersonIdResponses[keyof GetApiPersonByPersonIdResponses];

export type PatchApiPersonByPersonIdData = {
	body: UpdatePersonDto;
	path: {
		personId: number;
	};
	query?: never;
	url: '/api/person/{personId}';
};

export type PatchApiPersonByPersonIdErrors = {
	/**
	 * Not Authorized
	 */
	401: unknown;
	/**
	 * Not Allowed
	 */
	403: unknown;
};

export type PatchApiPersonByPersonIdResponses = {
	/**
	 * OK
	 */
	200: Person;
};

export type PatchApiPersonByPersonIdResponse =
	PatchApiPersonByPersonIdResponses[keyof PatchApiPersonByPersonIdResponses];

export type GetApiPersonByPersonIdGroupsData = {
	body?: never;
	path: {
		personId: number;
	};
	query?: never;
	url: '/api/person/{personId}/groups';
};

export type GetApiPersonByPersonIdGroupsErrors = {
	/**
	 * Not Authorized
	 */
	401: unknown;
	/**
	 * Not Allowed
	 */
	403: unknown;
};

export type GetApiPersonByPersonIdGroupsResponses = {
	/**
	 * OK
	 */
	200: Array<Group>;
};

export type GetApiPersonByPersonIdGroupsResponse =
	GetApiPersonByPersonIdGroupsResponses[keyof GetApiPersonByPersonIdGroupsResponses];

export type PostApiPersonByPersonIdSyncKeycloakData = {
	body?: never;
	path: {
		personId: number;
	};
	query?: never;
	url: '/api/person/{personId}/sync-keycloak';
};

export type PostApiPersonByPersonIdSyncKeycloakErrors = {
	/**
	 * Not Authorized
	 */
	401: unknown;
	/**
	 * Not Allowed
	 */
	403: unknown;
};

export type PostApiPersonByPersonIdSyncKeycloakResponses = {
	/**
	 * Created
	 */
	201: unknown;
};

export type GetApiProductData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/api/product';
};

export type GetApiProductErrors = {
	/**
	 * Not Authorized
	 */
	401: unknown;
	/**
	 * Not Allowed
	 */
	403: unknown;
};

export type GetApiProductResponses = {
	/**
	 * OK
	 */
	200: Array<Product>;
};

export type GetApiProductResponse = GetApiProductResponses[keyof GetApiProductResponses];

export type PostApiProductData = {
	body: CreateProductDto;
	path?: never;
	query?: never;
	url: '/api/product';
};

export type PostApiProductErrors = {
	/**
	 * Bad Request
	 */
	400: unknown;
	/**
	 * Not Authorized
	 */
	401: unknown;
	/**
	 * Not Allowed
	 */
	403: unknown;
};

export type PostApiProductResponses = {
	/**
	 * OK
	 */
	200: Product;
};

export type PostApiProductResponse = PostApiProductResponses[keyof PostApiProductResponses];

export type GetApiProductTallylistData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/api/product/tallylist';
};

export type GetApiProductTallylistErrors = {
	/**
	 * Not Authorized
	 */
	401: unknown;
	/**
	 * Not Allowed
	 */
	403: unknown;
};

export type GetApiProductTallylistResponses = {
	/**
	 * OK
	 */
	200: Blob | File;
};

export type GetApiProductTallylistResponse =
	GetApiProductTallylistResponses[keyof GetApiProductTallylistResponses];

export type DeleteApiProductByProductIdData = {
	body?: never;
	path: {
		productId: number;
	};
	query?: never;
	url: '/api/product/{productId}';
};

export type DeleteApiProductByProductIdErrors = {
	/**
	 * Not Authorized
	 */
	401: unknown;
	/**
	 * Not Allowed
	 */
	403: unknown;
};

export type DeleteApiProductByProductIdResponses = {
	/**
	 * No Content
	 */
	204: void;
};

export type DeleteApiProductByProductIdResponse =
	DeleteApiProductByProductIdResponses[keyof DeleteApiProductByProductIdResponses];

export type GetApiProductByProductIdData = {
	body?: never;
	path: {
		productId: number;
	};
	query?: never;
	url: '/api/product/{productId}';
};

export type GetApiProductByProductIdErrors = {
	/**
	 * Not Authorized
	 */
	401: unknown;
	/**
	 * Not Allowed
	 */
	403: unknown;
};

export type GetApiProductByProductIdResponses = {
	/**
	 * OK
	 */
	200: Product;
};

export type GetApiProductByProductIdResponse =
	GetApiProductByProductIdResponses[keyof GetApiProductByProductIdResponses];

export type PatchApiProductByProductIdData = {
	body: UpdateProductDto;
	path: {
		productId: number;
	};
	query?: never;
	url: '/api/product/{productId}';
};

export type PatchApiProductByProductIdErrors = {
	/**
	 * Not Authorized
	 */
	401: unknown;
	/**
	 * Not Allowed
	 */
	403: unknown;
};

export type PatchApiProductByProductIdResponses = {
	/**
	 * OK
	 */
	200: Product;
};

export type PatchApiProductByProductIdResponse =
	PatchApiProductByProductIdResponses[keyof PatchApiProductByProductIdResponses];

export type PostApiProductByProductIdMoveDownData = {
	body?: never;
	path: {
		productId: number;
	};
	query?: never;
	url: '/api/product/{productId}/move-down';
};

export type PostApiProductByProductIdMoveDownErrors = {
	/**
	 * Not Authorized
	 */
	401: unknown;
	/**
	 * Not Allowed
	 */
	403: unknown;
};

export type PostApiProductByProductIdMoveDownResponses = {
	/**
	 * Created
	 */
	201: unknown;
};

export type PostApiProductByProductIdMoveUpData = {
	body?: never;
	path: {
		productId: number;
	};
	query?: never;
	url: '/api/product/{productId}/move-up';
};

export type PostApiProductByProductIdMoveUpErrors = {
	/**
	 * Not Authorized
	 */
	401: unknown;
	/**
	 * Not Allowed
	 */
	403: unknown;
};

export type PostApiProductByProductIdMoveUpResponses = {
	/**
	 * Created
	 */
	201: unknown;
};

export type GetApiRecurringTransactionData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/api/recurring-transaction';
};

export type GetApiRecurringTransactionErrors = {
	/**
	 * Not Authorized
	 */
	401: unknown;
	/**
	 * Not Allowed
	 */
	403: unknown;
};

export type GetApiRecurringTransactionResponses = {
	/**
	 * OK
	 */
	200: Array<GetRecurringTransactionDto>;
};

export type GetApiRecurringTransactionResponse =
	GetApiRecurringTransactionResponses[keyof GetApiRecurringTransactionResponses];

export type PostApiRecurringTransactionData = {
	body: CreateRecurringTransactionDto;
	path?: never;
	query?: never;
	url: '/api/recurring-transaction';
};

export type PostApiRecurringTransactionErrors = {
	/**
	 * Bad Request
	 */
	400: unknown;
	/**
	 * Not Authorized
	 */
	401: unknown;
	/**
	 * Not Allowed
	 */
	403: unknown;
};

export type PostApiRecurringTransactionResponses = {
	/**
	 * OK
	 */
	200: GetRecurringTransactionDto;
};

export type PostApiRecurringTransactionResponse =
	PostApiRecurringTransactionResponses[keyof PostApiRecurringTransactionResponses];

export type DeleteApiRecurringTransactionByRecurringTransactionIdData = {
	body?: never;
	path: {
		recurringTransactionId: number;
	};
	query?: never;
	url: '/api/recurring-transaction/{recurringTransactionId}';
};

export type DeleteApiRecurringTransactionByRecurringTransactionIdErrors = {
	/**
	 * Not Authorized
	 */
	401: unknown;
	/**
	 * Not Allowed
	 */
	403: unknown;
};

export type DeleteApiRecurringTransactionByRecurringTransactionIdResponses = {
	/**
	 * No Content
	 */
	204: void;
};

export type DeleteApiRecurringTransactionByRecurringTransactionIdResponse =
	DeleteApiRecurringTransactionByRecurringTransactionIdResponses[keyof DeleteApiRecurringTransactionByRecurringTransactionIdResponses];

export type GetApiRecurringTransactionByRecurringTransactionIdData = {
	body?: never;
	path: {
		recurringTransactionId: number;
	};
	query?: never;
	url: '/api/recurring-transaction/{recurringTransactionId}';
};

export type GetApiRecurringTransactionByRecurringTransactionIdErrors = {
	/**
	 * Not Authorized
	 */
	401: unknown;
	/**
	 * Not Allowed
	 */
	403: unknown;
};

export type GetApiRecurringTransactionByRecurringTransactionIdResponses = {
	/**
	 * OK
	 */
	200: GetRecurringTransactionDto;
};

export type GetApiRecurringTransactionByRecurringTransactionIdResponse =
	GetApiRecurringTransactionByRecurringTransactionIdResponses[keyof GetApiRecurringTransactionByRecurringTransactionIdResponses];

export type PatchApiRecurringTransactionByRecurringTransactionIdData = {
	body: UpdateRecurringTransactionDto;
	path: {
		recurringTransactionId: number;
	};
	query?: never;
	url: '/api/recurring-transaction/{recurringTransactionId}';
};

export type PatchApiRecurringTransactionByRecurringTransactionIdErrors = {
	/**
	 * Not Authorized
	 */
	401: unknown;
	/**
	 * Not Allowed
	 */
	403: unknown;
};

export type PatchApiRecurringTransactionByRecurringTransactionIdResponses = {
	/**
	 * OK
	 */
	200: GetRecurringTransactionDto;
};

export type PatchApiRecurringTransactionByRecurringTransactionIdResponse =
	PatchApiRecurringTransactionByRecurringTransactionIdResponses[keyof PatchApiRecurringTransactionByRecurringTransactionIdResponses];

export type PostApiTransactionData = {
	body: CreateTransactionDto;
	path?: never;
	query?: never;
	url: '/api/transaction';
};

export type PostApiTransactionErrors = {
	/**
	 * Bad Request
	 */
	400: unknown;
	/**
	 * Not Authorized
	 */
	401: unknown;
	/**
	 * Not Allowed
	 */
	403: unknown;
};

export type PostApiTransactionResponses = {
	/**
	 * OK
	 */
	200: Transaction;
};

export type PostApiTransactionResponse =
	PostApiTransactionResponses[keyof PostApiTransactionResponses];

export type GetApiTransactionAccountByAccountIdData = {
	body?: never;
	path: {
		accountId: number;
	};
	query?: never;
	url: '/api/transaction/account/{accountId}';
};

export type GetApiTransactionAccountByAccountIdErrors = {
	/**
	 * Not Authorized
	 */
	401: unknown;
	/**
	 * Not Allowed
	 */
	403: unknown;
};

export type GetApiTransactionAccountByAccountIdResponses = {
	/**
	 * OK
	 */
	200: Array<TransactionSaldoDto>;
};

export type GetApiTransactionAccountByAccountIdResponse =
	GetApiTransactionAccountByAccountIdResponses[keyof GetApiTransactionAccountByAccountIdResponses];

export type DeleteApiTransactionByTransactionIdData = {
	body?: never;
	path: {
		transactionId: number;
	};
	query?: never;
	url: '/api/transaction/{transactionId}';
};

export type DeleteApiTransactionByTransactionIdErrors = {
	/**
	 * Not Authorized
	 */
	401: unknown;
	/**
	 * Not Allowed
	 */
	403: unknown;
};

export type DeleteApiTransactionByTransactionIdResponses = {
	/**
	 * No Content
	 */
	204: void;
};

export type DeleteApiTransactionByTransactionIdResponse =
	DeleteApiTransactionByTransactionIdResponses[keyof DeleteApiTransactionByTransactionIdResponses];

export type GetApiTransactionByTransactionIdData = {
	body?: never;
	path: {
		transactionId: number;
	};
	query?: never;
	url: '/api/transaction/{transactionId}';
};

export type GetApiTransactionByTransactionIdErrors = {
	/**
	 * Not Authorized
	 */
	401: unknown;
	/**
	 * Not Allowed
	 */
	403: unknown;
};

export type GetApiTransactionByTransactionIdResponses = {
	/**
	 * OK
	 */
	200: Transaction;
};

export type GetApiTransactionByTransactionIdResponse =
	GetApiTransactionByTransactionIdResponses[keyof GetApiTransactionByTransactionIdResponses];

export type PatchApiTransactionByTransactionIdData = {
	body: UpdateTransactionDto;
	path: {
		transactionId: number;
	};
	query?: never;
	url: '/api/transaction/{transactionId}';
};

export type PatchApiTransactionByTransactionIdErrors = {
	/**
	 * Not Authorized
	 */
	401: unknown;
	/**
	 * Not Allowed
	 */
	403: unknown;
};

export type PatchApiTransactionByTransactionIdResponses = {
	/**
	 * OK
	 */
	200: Transaction;
};

export type PatchApiTransactionByTransactionIdResponse =
	PatchApiTransactionByTransactionIdResponses[keyof PatchApiTransactionByTransactionIdResponses];

export type DeleteApiTransactionByTransactionIdReceiptData = {
	body?: never;
	path: {
		transactionId: number;
	};
	query?: never;
	url: '/api/transaction/{transactionId}/receipt';
};

export type DeleteApiTransactionByTransactionIdReceiptErrors = {
	/**
	 * Not Authorized
	 */
	401: unknown;
	/**
	 * Not Allowed
	 */
	403: unknown;
};

export type DeleteApiTransactionByTransactionIdReceiptResponses = {
	/**
	 * No Content
	 */
	204: void;
};

export type DeleteApiTransactionByTransactionIdReceiptResponse =
	DeleteApiTransactionByTransactionIdReceiptResponses[keyof DeleteApiTransactionByTransactionIdReceiptResponses];

export type GetApiTransactionByTransactionIdReceiptData = {
	body?: never;
	path: {
		transactionId: number;
	};
	query?: never;
	url: '/api/transaction/{transactionId}/receipt';
};

export type GetApiTransactionByTransactionIdReceiptErrors = {
	/**
	 * Not Authorized
	 */
	401: unknown;
	/**
	 * Not Allowed
	 */
	403: unknown;
};

export type GetApiTransactionByTransactionIdReceiptResponses = {
	/**
	 * OK
	 */
	200: Blob | File;
};

export type GetApiTransactionByTransactionIdReceiptResponse =
	GetApiTransactionByTransactionIdReceiptResponses[keyof GetApiTransactionByTransactionIdReceiptResponses];

export type PostApiTransactionByTransactionIdReceiptData = {
	body: {
		receipt?: Blob | File;
	};
	path: {
		transactionId: number;
	};
	query?: never;
	url: '/api/transaction/{transactionId}/receipt';
};

export type PostApiTransactionByTransactionIdReceiptErrors = {
	/**
	 * Not Authorized
	 */
	401: unknown;
	/**
	 * Not Allowed
	 */
	403: unknown;
};

export type PostApiTransactionByTransactionIdReceiptResponses = {
	/**
	 * Created
	 */
	201: unknown;
};

export type GetByFileNameData = {
	body?: never;
	path: {
		fileName: string;
	};
	query?: never;
	url: '/{fileName}';
};

export type GetByFileNameResponses = {
	/**
	 * OK
	 */
	200: unknown;
};

export type ClientOptions = {
	baseUrl: 'http://localhost:8080' | (string & {});
};
