// This file is auto-generated by @hey-api/openapi-ts

export type Account = {
    id?: number;
    name?: string;
    active?: boolean;
};

export type CreateAccountDto = {
    name: string;
    active: boolean;
};

export type CreatePersonDto = {
    name: string;
    room: string;
    paysFloorFees: boolean;
};

export type CreateProductDto = {
    name: string;
    price?: number;
};

export type Person = {
    id?: number;
    name?: string;
    room?: string;
    paysFloorFees?: boolean;
    accountId?: number;
};

export type Product = {
    id?: number;
    name?: string;
    price?: number;
};

export type UpdateAccountDto = {
    name?: string | null;
    active?: boolean | null;
};

export type UpdatePersonDto = {
    name?: string | null;
    room?: string | null;
    paysFloorFees?: boolean | null;
};

export type UpdateProductDto = {
    name?: string | null;
    price?: number | null;
};

export type GetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type GetResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiAccountData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/account';
};

export type GetApiAccountErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type GetApiAccountResponses = {
    /**
     * OK
     */
    200: Array<Account>;
};

export type GetApiAccountResponse = GetApiAccountResponses[keyof GetApiAccountResponses];

export type PostApiAccountData = {
    body: CreateAccountDto;
    path?: never;
    query?: never;
    url: '/api/account';
};

export type PostApiAccountErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type PostApiAccountResponses = {
    /**
     * OK
     */
    200: Account;
};

export type PostApiAccountResponse = PostApiAccountResponses[keyof PostApiAccountResponses];

export type DeleteApiAccountByAccountIdDData = {
    body?: never;
    path: {
        accountId: number;
    };
    query?: never;
    url: '/api/account/{accountId}:\\d+';
};

export type DeleteApiAccountByAccountIdDErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type DeleteApiAccountByAccountIdDResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteApiAccountByAccountIdDResponse = DeleteApiAccountByAccountIdDResponses[keyof DeleteApiAccountByAccountIdDResponses];

export type GetApiAccountByAccountIdDData = {
    body?: never;
    path: {
        accountId: number;
    };
    query?: never;
    url: '/api/account/{accountId}:\\d+';
};

export type GetApiAccountByAccountIdDErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type GetApiAccountByAccountIdDResponses = {
    /**
     * OK
     */
    200: Account;
};

export type GetApiAccountByAccountIdDResponse = GetApiAccountByAccountIdDResponses[keyof GetApiAccountByAccountIdDResponses];

export type PatchApiAccountByAccountIdDData = {
    body: UpdateAccountDto;
    path: {
        accountId: number;
    };
    query?: never;
    url: '/api/account/{accountId}:\\d+';
};

export type PatchApiAccountByAccountIdDErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type PatchApiAccountByAccountIdDResponses = {
    /**
     * OK
     */
    200: Account;
};

export type PatchApiAccountByAccountIdDResponse = PatchApiAccountByAccountIdDResponses[keyof PatchApiAccountByAccountIdDResponses];

export type GetApiPersonData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/person';
};

export type GetApiPersonErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type GetApiPersonResponses = {
    /**
     * OK
     */
    200: Array<Person>;
};

export type GetApiPersonResponse = GetApiPersonResponses[keyof GetApiPersonResponses];

export type PostApiPersonData = {
    body: CreatePersonDto;
    path?: never;
    query?: never;
    url: '/api/person';
};

export type PostApiPersonErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type PostApiPersonResponses = {
    /**
     * OK
     */
    200: Person;
};

export type PostApiPersonResponse = PostApiPersonResponses[keyof PostApiPersonResponses];

export type DeleteApiPersonByPersonIdDData = {
    body?: never;
    path: {
        personId: number;
    };
    query?: never;
    url: '/api/person/{personId}:\\d+';
};

export type DeleteApiPersonByPersonIdDErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type DeleteApiPersonByPersonIdDResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteApiPersonByPersonIdDResponse = DeleteApiPersonByPersonIdDResponses[keyof DeleteApiPersonByPersonIdDResponses];

export type GetApiPersonByPersonIdDData = {
    body?: never;
    path: {
        personId: number;
    };
    query?: never;
    url: '/api/person/{personId}:\\d+';
};

export type GetApiPersonByPersonIdDErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type GetApiPersonByPersonIdDResponses = {
    /**
     * OK
     */
    200: Person;
};

export type GetApiPersonByPersonIdDResponse = GetApiPersonByPersonIdDResponses[keyof GetApiPersonByPersonIdDResponses];

export type PatchApiPersonByPersonIdDData = {
    body: UpdatePersonDto;
    path: {
        personId: number;
    };
    query?: never;
    url: '/api/person/{personId}:\\d+';
};

export type PatchApiPersonByPersonIdDErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type PatchApiPersonByPersonIdDResponses = {
    /**
     * OK
     */
    200: Person;
};

export type PatchApiPersonByPersonIdDResponse = PatchApiPersonByPersonIdDResponses[keyof PatchApiPersonByPersonIdDResponses];

export type GetApiProductData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/product';
};

export type GetApiProductErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type GetApiProductResponses = {
    /**
     * OK
     */
    200: Array<Product>;
};

export type GetApiProductResponse = GetApiProductResponses[keyof GetApiProductResponses];

export type PostApiProductData = {
    body: CreateProductDto;
    path?: never;
    query?: never;
    url: '/api/product';
};

export type PostApiProductErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type PostApiProductResponses = {
    /**
     * OK
     */
    200: Product;
};

export type PostApiProductResponse = PostApiProductResponses[keyof PostApiProductResponses];

export type DeleteApiProductByProductIdDData = {
    body?: never;
    path: {
        productId: number;
    };
    query?: never;
    url: '/api/product/{productId}:\\d+';
};

export type DeleteApiProductByProductIdDErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type DeleteApiProductByProductIdDResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteApiProductByProductIdDResponse = DeleteApiProductByProductIdDResponses[keyof DeleteApiProductByProductIdDResponses];

export type GetApiProductByProductIdDData = {
    body?: never;
    path: {
        productId: number;
    };
    query?: never;
    url: '/api/product/{productId}:\\d+';
};

export type GetApiProductByProductIdDErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type GetApiProductByProductIdDResponses = {
    /**
     * OK
     */
    200: Product;
};

export type GetApiProductByProductIdDResponse = GetApiProductByProductIdDResponses[keyof GetApiProductByProductIdDResponses];

export type PatchApiProductByProductIdDData = {
    body: UpdateProductDto;
    path: {
        productId: number;
    };
    query?: never;
    url: '/api/product/{productId}:\\d+';
};

export type PatchApiProductByProductIdDErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type PatchApiProductByProductIdDResponses = {
    /**
     * OK
     */
    200: Product;
};

export type PatchApiProductByProductIdDResponse = PatchApiProductByProductIdDResponses[keyof PatchApiProductByProductIdDResponses];

export type GetByFileNameData = {
    body?: never;
    path: {
        fileName: string;
    };
    query?: never;
    url: '/{fileName}';
};

export type GetByFileNameResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: 'http://localhost:8080' | (string & {});
};